# Generated by Django 4.1.5 on 2023-02-16 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_username"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="username",),
    ]
