# Generated by Django 4.1.5 on 2023-02-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="image/", verbose_name="Аватарка"
            ),
        ),
    ]
