# Generated by Django 4.1.5 on 2023-02-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_alter_lesson_options_remove_course_lssn_lesson_crss"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video",
            field=models.URLField(blank=True, null=True, verbose_name="Видео"),
        ),
    ]
